### ISSUE TITLE
Backward Compatibility GlobalValueTransformerLoader

### ISSUE THREAD

**Issue by mesut** [zalando-stups/java-sproc-wrapper#67]
In the previous versions **GlobalValueTransformerLoader** scans **"de.zalando"** path by default in order to find and register classes which are annotated with **@GlobalValueTransforme**r. After base package of the service was changed to **"org.zalando"**, the **GlobalValueTransformerLoader** classes no longer scans **"de.zalando"** path. 

It is better to scan both namespaces which are **"org.zalando"** and **"de.zalando"** to not force library user to change their package structure. If the any value transformer is not registered by **GlobalValueTransformerLoader**, it doesn't throw any error.  that can cause  issues for the library users in the production.

**Comment by vadeg** [comment]
Added support to multiple namespaces. See #87

**Comment by gmariotti** [comment]
Hi, I'm looking into updating our usage of sproc-wrapper to the latest version and I think I spotted a bug in the implementation of the multi-package support. [Here](https://github.com/zalando-stups/java-sproc-wrapper/blob/master/src/main/java/org/zalando/sprocwrapper/globalvaluetransformer/GlobalValueTransformerLoader.java#L51-L55) instead of `filter(Strings::isNullOrEmpty)` shouldn't it be `filter(x -> !Strings.isNullOrEmpty(x))`?

**Comment by vadeg** [comment]
@gmariotti great catch! Thank you! I have created a fix #94
